#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: e661f3a
#
Name     : R-htmlwidgets
Version  : 1.6.3
Release  : 61
URL      : https://cran.r-project.org/src/contrib/htmlwidgets_1.6.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/htmlwidgets_1.6.3.tar.gz
Summary  : HTML Widgets for R
Group    : Development/Tools
License  : MIT
Requires: R-htmltools
Requires: R-jsonlite
Requires: R-knitr
Requires: R-rmarkdown
Requires: R-yaml
BuildRequires : R-htmltools
BuildRequires : R-jsonlite
BuildRequires : R-knitr
BuildRequires : R-rmarkdown
BuildRequires : R-yaml
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
contexts including the R console, 'R Markdown' documents, and 'Shiny'
    web applications.

%prep
%setup -q -n htmlwidgets
pushd ..
cp -a htmlwidgets buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1700988400

%install
export SOURCE_DATE_EPOCH=1700988400
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/htmlwidgets/DESCRIPTION
/usr/lib64/R/library/htmlwidgets/INDEX
/usr/lib64/R/library/htmlwidgets/LICENSE
/usr/lib64/R/library/htmlwidgets/Meta/Rd.rds
/usr/lib64/R/library/htmlwidgets/Meta/features.rds
/usr/lib64/R/library/htmlwidgets/Meta/hsearch.rds
/usr/lib64/R/library/htmlwidgets/Meta/links.rds
/usr/lib64/R/library/htmlwidgets/Meta/nsInfo.rds
/usr/lib64/R/library/htmlwidgets/Meta/package.rds
/usr/lib64/R/library/htmlwidgets/Meta/vignette.rds
/usr/lib64/R/library/htmlwidgets/NAMESPACE
/usr/lib64/R/library/htmlwidgets/NEWS.md
/usr/lib64/R/library/htmlwidgets/R/htmlwidgets
/usr/lib64/R/library/htmlwidgets/R/htmlwidgets.rdb
/usr/lib64/R/library/htmlwidgets/R/htmlwidgets.rdx
/usr/lib64/R/library/htmlwidgets/doc/develop_advanced.R
/usr/lib64/R/library/htmlwidgets/doc/develop_advanced.Rmd
/usr/lib64/R/library/htmlwidgets/doc/develop_advanced.html
/usr/lib64/R/library/htmlwidgets/doc/develop_intro.R
/usr/lib64/R/library/htmlwidgets/doc/develop_intro.Rmd
/usr/lib64/R/library/htmlwidgets/doc/develop_intro.html
/usr/lib64/R/library/htmlwidgets/doc/develop_sizing.Rmd
/usr/lib64/R/library/htmlwidgets/doc/develop_sizing.html
/usr/lib64/R/library/htmlwidgets/doc/index.html
/usr/lib64/R/library/htmlwidgets/help/AnIndex
/usr/lib64/R/library/htmlwidgets/help/aliases.rds
/usr/lib64/R/library/htmlwidgets/help/htmlwidgets.rdb
/usr/lib64/R/library/htmlwidgets/help/htmlwidgets.rdx
/usr/lib64/R/library/htmlwidgets/help/paths.rds
/usr/lib64/R/library/htmlwidgets/html/00Index.html
/usr/lib64/R/library/htmlwidgets/html/R.css
/usr/lib64/R/library/htmlwidgets/templates/widget_js.txt
/usr/lib64/R/library/htmlwidgets/templates/widget_r.txt
/usr/lib64/R/library/htmlwidgets/tests/testthat.R
/usr/lib64/R/library/htmlwidgets/tests/testthat/test-htmlwidgets.R
/usr/lib64/R/library/htmlwidgets/tests/testthat/test-pandoc.R
/usr/lib64/R/library/htmlwidgets/www/htmlwidgets.js
